#include "devils_engine/originator/script_translate.h"

#include <algorithm>
#include <format>
#include <ranges>

#include <devils_script/script_ast.h>
#include <devils_script/system.h>

#include "devils_engine/utils/core.h"

namespace devils_engine {
namespace originator {

namespace {
namespace ds = devils_script;

// Функции `ds`, у которых имя в GLSL то же самое. Словарь совпадает не случайно: математика ds это
// буквально имена GLSL, и это было известно до перевода — здесь только зафиксирована арность, потому
// что арность GLSL проверит сам, а сообщение об ошибке хочется получить со ссылкой на текст ds.
struct direct_function {
  std::string_view name;
  uint32_t min_args;
  uint32_t max_args;
};

constexpr direct_function direct_functions[] = {
  {"max", 2, 2},        {"min", 2, 2},   {"abs", 1, 1},        {"ceil", 1, 1},
  {"floor", 1, 1},      {"round", 1, 1}, {"trunc", 1, 1},      {"exp", 1, 1},
  {"sqrt", 1, 1},       {"inversesqrt", 1, 1},                 {"sin", 1, 1},
  {"cos", 1, 1},        {"asin", 1, 1},  {"acos", 1, 1},       {"tan", 1, 1},
  {"atan", 1, 2},       {"sign", 1, 1},  {"fma", 3, 3},        {"fract", 1, 1},
  {"mix", 3, 3},        {"clamp", 3, 3}, {"smoothstep", 3, 3}, {"step", 2, 2},
};

// Что не переводится и ПОЧЕМУ. Причина у каждого своя, и общее «не поддерживается» здесь не годится:
// одно упирается в динамическую память, другое в отсутствие соли в AST, третье вообще не про счёт.
struct refusal {
  std::string_view name;
  std::string_view reason;
};

constexpr refusal refusals[] = {
  {"chance", "the per-site salt is generated by ds's emitter at compile time and is not in the AST; "
             "translating randomness needs the compiled container or the salt from ds"},
  {"random", "the per-site salt is generated by ds's emitter at compile time and is not in the AST"},
  {"rndmix", "the per-site salt is generated by ds's emitter at compile time and is not in the AST"},
  {"rndmix1", "the per-site salt is generated by ds's emitter at compile time and is not in the AST"},
  {"list", "a list needs dynamic memory per element, which a shader invocation does not have"},
  {"add_to", "a list needs dynamic memory per element, which a shader invocation does not have"},
  {"is_in", "a list needs dynamic memory per element, which a shader invocation does not have"},
  {"remove_from", "a list needs dynamic memory per element, which a shader invocation does not have"},
  {"ctx_save", "a saved slot translates to a shader local ONLY when it is written before it is read on "
               "every path inside the element, and that check does not exist yet"},
  {"ctx_set", "context storage has no shader equivalent"},
  {"assert", "diagnostics do not enter a queue"},
  {"trace", "diagnostics do not enter a queue"},
  {"select", "block forms other than value_or are not translated yet"},
  {"sequence", "block forms other than value_or are not translated yet"},
  {"switch", "block forms other than value_or are not translated yet"},
  {"execute", "a sub-script would need its own translation and its own frame"},
};

std::string_view glsl_buffer_type(const field_base::values base) noexcept {
  switch (base) {
    case field_base::v: return "float";
    case field_base::ui: return "uint";
    case field_base::i: return "int";
    default: return {};
  }
}

struct translator {
  const tavl::parser* parser = nullptr;
  std::string_view program_name;
  std::span<const translated_field> inputs;
  script_program::result_kind kind = script_program::result_kind::number;
  std::vector<std::string>* arguments = nullptr;

  std::string_view text(const tavl::token& token) const {
    return parser->content(token.span);
  }

  [[noreturn]] void refuse(const tavl::token& token, const std::string_view& what) const {
    utils::error{}("originator script '{}' @ {}:{}: {}", program_name, token.span.line, token.span.column, what);
  }

  // Аргумент `ctx:arg:имя` становится push-константой. Порядок объявления — порядок первой встречи,
  // и он же уезжает наружу: хост обязан выкладывать байты в нём, а не догадываться.
  std::string argument(const std::string_view& path, const tavl::token& token) const {
    static constexpr std::string_view prefix = "ctx:arg:";
    const auto name = path.substr(prefix.size());
    if (name.empty()) {
      refuse(token, "ctx:arg: names no argument");
    }

    const auto found = std::find(arguments->begin(), arguments->end(), name);
    if (found == arguments->end()) {
      arguments->emplace_back(name);
    }
    return std::format("args.arg_{}", name);
  }

  // Чтение поля своего элемента. Никакого другого обращения к данным у программы нет — она
  // структурно pointwise, и именно поэтому один её вызов это одна инвокация без синхронизации.
  std::string field(const std::string_view& name, const tavl::token& token) const {
    for (size_t i = 0; i < inputs.size(); ++i) {
      if (inputs[i].name != name) continue;
      const auto type = glsl_buffer_type(inputs[i].base);
      return type == "float" ? std::format("in_{}.data[index]", i)
                             : std::format("float(in_{}.data[index])", i);
    }

    refuse(token, std::format("'{}' is not one of the bound fields: a program is compiled against the names of "
                              "its bindings, and an unbound name cannot become anything",
                              name));
  }

  std::string value(const tavl::node_view node) const;
  std::string block(const tavl::node_view node) const;
  std::string call(const std::string_view& callee, const tavl::node_view args, const tavl::token& token) const;
  std::string binary(const std::string_view& op, const tavl::node_view node) const;
};

std::string translator::binary(const std::string_view& op, const tavl::node_view node) const {
  const auto& token = node.root().token;

  if (node.size() == 1) {
    const auto operand = value(node.child(0));
    if (op == "-") return std::format("(-{})", operand);
    if (op == "+") return operand;
    if (op == "not") return std::format("(!{})", operand);
    refuse(token, std::format("unary operator '{}' has no shader form", op));
  }

  if (node.size() != 2) {
    refuse(token, std::format("operator '{}' got {} operands", op, node.size()));
  }

  const auto left = value(node.child(0));
  const auto right = value(node.child(1));

  if (op == "+" || op == "-" || op == "*" || op == "/" || op == "<" || op == ">" || op == "<=" || op == ">=") {
    return std::format("({} {} {})", left, op, right);
  }
  if (op == "%") {
    // У float остатка в GLSL нет как оператора, а `mod` считает то же, что `%` у ds над числами.
    return std::format("mod({}, {})", left, right);
  }
  if (op == "and") return std::format("({} && {})", left, right);
  if (op == "or") return std::format("({} || {})", left, right);

  refuse(token, std::format("operator '{}' has no shader form", op));
}

std::string translator::call(const std::string_view& callee,
                             const tavl::node_view args,
                             const tavl::token& token) const {
  for (const auto& entry : refusals) {
    if (entry.name == callee) {
      refuse(token, std::format("'{}' does not translate: {}", callee, entry.reason));
    }
  }

  // `value_or = { условие, тогда, иначе }` — тройная форма, та самая, из которой в GN01 собрано
  // правило биома вложением. Другие арности ds допускает, и они переводятся тем же тернарником, но
  // непроверенная догадка о порядке аргументов означала бы правило, считающее не то.
  if (callee == "value_or") {
    if (args.size() != 3) {
      refuse(token, std::format("'value_or' with {} arguments is not translated; the three-argument form "
                                "(condition, then, else) is",
                                args.size()));
    }
    // Ветви переводятся ОТДЕЛЬНЫМИ ОПЕРАТОРАМИ, а не аргументами одного вызова: порядок вычисления
    // аргументов функции в C++ не определён, а перевод не чистая функция — он попутно собирает список
    // аргументов программы, и от их порядка зависит раскладка push-константы. Собранная as-is
    // раскладка зависела бы от компилятора: у gcc список выходил перевёрнутым, и тест это поймал.
    const auto condition = value(args.child(0));
    const auto positive = value(args.child(1));
    const auto negative = value(args.child(2));
    return std::format("({} ? {} : {})", condition, positive, negative);
  }

  // `inv` — единственная арифметическая функция ds без тёзки в GLSL.
  if (callee == "inv") {
    if (args.size() != 1) {
      refuse(token, std::format("'inv' takes one argument, got {}", args.size()));
    }
    return std::format("(1.0 / {})", value(args.child(0)));
  }

  for (const auto& entry : direct_functions) {
    if (entry.name != callee) continue;
    if (args.size() < entry.min_args || args.size() > entry.max_args) {
      refuse(token, std::format("'{}' takes {}..{} arguments, got {}", callee, entry.min_args, entry.max_args,
                                args.size()));
    }

    // Цикл, а не свёртка аргументов в один вызов, по той же причине: порядок здесь ЗНАЧИМ, потому
    // что перевод попутно нумерует аргументы программы.
    std::string result(callee);
    result.push_back('(');
    for (size_t i = 0; i < args.size(); ++i) {
      if (i != 0) result.append(", ");
      const auto argument = value(args.child(i));
      result.append(argument);
    }
    result.push_back(')');
    return result;
  }

  refuse(token, std::format("'{}' is not a function the translator knows; the vocabulary is the GLSL-named "
                            "arithmetic of ds plus value_or and inv",
                            callee));
}

// Блок, который НЕ является списком аргументов вызова, — это комбинатор: у числовой программы
// строки складываются, у предикатной сходятся по И. Так их и соединяет сам ds, и в переводе это
// правило то же, а не своё.
std::string translator::block(const tavl::node_view node) const {
  if (node.size() == 0) {
    refuse(node.root().token, "an empty block computes nothing");
  }
  if (node.size() == 1) {
    return value(node.child(0));
  }

  const std::string_view combinator = kind == script_program::result_kind::predicate ? " && " : " + ";
  std::string result = "(";
  for (size_t i = 0; i < node.size(); ++i) {
    if (i != 0) result.append(combinator);
    result.append(value(node.child(i)));
  }
  result.push_back(')');
  return result;
}

std::string translator::value(const tavl::node_view node) const {
  const auto& root = node.root();

  switch (root.type) {
    case tavl::node_type::token: {
      const auto content = text(root.token);
      switch (root.token.type) {
        case tavl::token_type::number_int:
        case tavl::token_type::number_uint:
        case tavl::token_type::number_float:
          // Через float(): целочисленный литерал в GLSL это int, и во float-выражении он бы менял тип.
          return std::format("float({})", content);
        case tavl::token_type::boolean: return std::string(content);
        case tavl::token_type::identifier: return field(content, root.token);
        case tavl::token_type::unrecognized: {
          // Путь области (`a.b:c`) приезжает одним нераспознанным токеном. Единственный путь, который
          // здесь имеет смысл, — аргумент: до соседа программе не добраться, а больше в скоупе ничего
          // и нет.
          if (content.starts_with("ctx:arg:")) {
            return argument(content, root.token);
          }
          refuse(root.token, std::format("scope path '{}' has no shader form: a program can read the fields of "
                                         "its own element and its arguments, and nothing else",
                                         content));
        }
        default:
          refuse(root.token, std::format("token '{}' of type '{}' has no shader form", content,
                                         tavl::to_string(root.token.type)));
      }
    }

    case tavl::node_type::pair: {
      const auto op = root.token.exists() ? text(root.token) : std::string_view{};
      // `=` и `?=` у ds это операторы ВЫЗОВА, а не присваивания: `f = {...}` означает `f(...)`.
      // Вызов с пустым оператором — та же запись через скобки. Всё остальное — математика.
      if (op.empty() || op == "=" || op == "?=") {
        if (node.size() != 2) {
          refuse(root.token, std::format("a call needs a callee and its arguments, got {} parts", node.size()));
        }
        const auto callee = node.child(0);
        if (callee.root().type != tavl::node_type::token) {
          refuse(root.token, "the callee of a call is not a name");
        }
        return call(text(callee.root().token), node.child(1), callee.root().token);
      }
      return binary(op, node);
    }

    case tavl::node_type::object:
    case tavl::node_type::row:
    case tavl::node_type::array:
    case tavl::node_type::tuple:
      return block(node);

    default:
      refuse(root.token, std::format("node of type '{}' has no shader form", int(root.type)));
  }
}
} // namespace

translation translate_to_glsl(const std::string_view& name,
                             const std::string_view& source,
                             const std::span<const translated_field>& inputs,
                             const translated_field& output,
                             const script_program::result_kind kind,
                             const uint32_t group_size) {
  if (inputs.size() > max_script_inputs) {
    utils::error{}("originator script '{}': {} input fields, at most {} are supported", name, inputs.size(),
                   max_script_inputs);
  }
  if (glsl_buffer_type(output.base).empty()) {
    utils::error{}("originator script '{}': output field '{}' has storage kind '{}', which a shader buffer has no "
                   "type for; the queue takes the 32-bit kinds v, ui and i",
                   name, output.name, to_string(output.base));
  }
  for (const auto& field : inputs) {
    if (!glsl_buffer_type(field.base).empty()) continue;
    utils::error{}("originator script '{}': input field '{}' has storage kind '{}', which a shader buffer has no "
                   "type for; the queue takes the 32-bit kinds v, ui and i",
                   name, field.name, to_string(field.base));
  }

  // Парсер настраивает САМА система ds: приоритеты и фиксность операторов объявлены в ней, и второй
  // их список разъехался бы с первым молча.
  ds::system system;
  system.init_basic_functions();
  system.init_math();

  tavl::parser parser;
  system.configure_parser(parser);

  std::vector<tavl::node> nodes;
  try {
    nodes = ds::make_script_ast(parser, source);
  } catch (const std::exception& error) {
    utils::error{}("originator script '{}': could not parse for translation: {}", name, error.what());
  }
  if (nodes.empty()) {
    utils::error{}("originator script '{}': the program is empty", name);
  }

  translation result;
  result.group_size = group_size;

  translator emitter;
  emitter.parser = &parser;
  emitter.program_name = name;
  emitter.inputs = inputs;
  emitter.kind = kind;
  emitter.arguments = &result.arguments;

  const auto expression = emitter.value(tavl::node_view{nodes});

  // Преобразование результата в род поля повторяет `store_component` НАРОЧНО: две разные записи одного
  // и того же значения дали бы два разных поля, и разница проявилась бы только на границах диапазона.
  // Верхнюю границу float32 при этом не представляет точно (`4294967295` округляется до `4294967296`),
  // и это объявленное расхождение путей на самом краю, а не незамеченная ошибка.
  std::string stored;
  const auto output_type = glsl_buffer_type(output.base);
  const auto numeric = kind == script_program::result_kind::predicate
                         ? std::format("(({}) ? 1.0 : 0.0)", expression)
                         : std::format("({})", expression);
  if (output.base == field_base::v) {
    stored = numeric;
  } else if (output.base == field_base::ui) {
    stored = std::format("uint(clamp({}, 0.0, 4294967295.0))", numeric);
  } else {
    stored = std::format("int(clamp({}, -2147483648.0, 2147483647.0))", numeric);
  }

  // ШЕЙДЕР НЕСЁТ СВОЁ ПРОИСХОЖДЕНИЕ. Заголовок-комментарий отвечает на вопрос «как именно перевод
  // перенёс скрипт»: исходный текст ds, какой биндинг какому полю соответствует и как выложена
  // push-константа. Без этого сверять сторону хоста приходится по памяти, а перепутанный порядок
  // аргументов не выглядит ошибкой ни с той, ни с другой стороны. Комментарий бесплатен: glslc
  // снимает его при компиляции.
  std::string text;
  text.append(std::format("// Переведено из devils_script: программа '{}'.\n//\n", name));
  text.append("// ИСХОДНЫЙ ТЕКСТ:\n");
  for (const auto line : std::views::split(source, '\n')) {
    text.append("//   ");
    text.append(std::string_view(line.begin(), line.end()));
    text.push_back('\n');
  }
  text.append("//\n// ПРИВЯЗКИ:\n");
  for (size_t i = 0; i < inputs.size(); ++i) {
    text.append(std::format("//   binding {} = вход '{}' ({})\n", i, inputs[i].name, to_string(inputs[i].base)));
  }
  text.append(std::format("//   binding {} = выход '{}' ({})\n", inputs.size(), output.name, to_string(output.base)));
  text.append("//\n// PUSH-КОНСТАНТА, байт за байтом:\n//   0: uint count\n");
  for (size_t i = 0; i < result.arguments.size(); ++i) {
    text.append(std::format("//   {}: float {}\n", sizeof(uint32_t) + i * sizeof(float), result.arguments[i]));
  }
  text.append(std::format("//\n// ВЫРАЖЕНИЕ:\n//   {}\n\n", expression));

  text.append("#version 450\n\n");
  text.append(std::format("layout(local_size_x = {}) in;\n\n", group_size));

  for (size_t i = 0; i < inputs.size(); ++i) {
    text.append(std::format("layout(std430, binding = {}) readonly buffer in_{}_buffer {{ {} data[]; }} in_{};\n",
                            i, i, glsl_buffer_type(inputs[i].base), i));
  }
  text.append(std::format("layout(std430, binding = {}) writeonly buffer out_buffer {{ {} data[]; }} out_field;\n\n",
                          inputs.size(), output_type));

  text.append("layout(push_constant) uniform arguments_block {\n  uint count;\n");
  for (const auto& argument : result.arguments) {
    text.append(std::format("  float arg_{};\n", argument));
  }
  text.append("} args;\n\n");

  // Индекс собирается из ДВУХ осей: гарантированный минимум `maxComputeWorkGroupCount[0]` это 65535,
  // и одномерный диспатч кончается на 4.2 млн элементов при группе 64 — а буферы генератора бывают
  // и больше. Охранник нужен потому, что диспатч кратен размеру группы, а число элементов нет.
  text.append("void main() {\n");
  text.append("  uint group = gl_WorkGroupID.y * gl_NumWorkGroups.x + gl_WorkGroupID.x;\n");
  text.append("  uint index = group * gl_WorkGroupSize.x + gl_LocalInvocationID.x;\n");
  text.append("  if (index >= args.count) return;\n\n");
  text.append(std::format("  out_field.data[index] = {};\n", stored));
  text.append("}\n");

  result.source = std::move(text);
  return result;
}

} // namespace originator
} // namespace devils_engine
